version: '3'
services:
  mongodb:
    container_name: 'mongodb'
    image: 'mongodb'
    build:
      context: .
      dockerfile: ./mongo.dockerfile
    ports:
    - "27017:27017"

  monolith:
    container_name: 'monolith'
    image: 'monolith'
    build:
      context: .
      dockerfile: ./monolith.dockerfile
    ports:
    - "8000:8080"
    links:
    - mongodb